### ISSUE TITLE
Error "No content"

### ISSUE THREAD

**Issue by johannesbonn** [CWempe/rest2influxdb#1]
Hi,
thank your for your effort to realize such a program. I have the following problem. I defined my config and start the conversion for one item. This is my output:

`MacJo:rest2influxdb-master johannes$ ./rest2influxdb.sh HK_WEATHER1Aussen_Temperature
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

### timestamps
item: HK_WEATHER1Aussen_Temperature
10y:  
1y:   
1m:   
1w:   
1d:   
8h:   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0   4586      0 --:--:-- --:--:-- --:--:--  4679
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0   9807      0 --:--:-- --:--:-- --:--:--  9920
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0   8069      0 --:--:-- --:--:-- --:--:--  8266
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0   6910      0 --:--:-- --:--:-- --:--:--  7085
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0   6930      0 --:--:-- --:--:-- --:--:--  6888
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0   8570      0 --:--:-- --:--:-- --:--:--  8857

### found values: 
./rest2influxdb.sh: line 64: [: 1: unary operator expected
sed: 1: "101,+200p": expected context address
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 9e281da4-5ee7-11e7-8113-000000000000
X-Influxdb-Version: 1.3.0
Date: Sun, 02 Jul 2017 05:30:54 GMT

./rest2influxdb.sh: line 64: [: 101: unary operator expected
sed: 1: "201,+300p": expected context address
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 9e2f42f7-5ee7-11e7-8114-000000000000
X-Influxdb-Version: 1.3.0
Date: Sun, 02 Jul 2017 05:30:54 GMT

./rest2influxdb.sh: line 64: [: 201: unary operator expected
sed: 1: "301,+400p": expected context address
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 9e3849f1-5ee7-11e7-8115-000000000000
X-Influxdb-Version: 1.3.0
Date: Sun, 02 Jul 2017 05:30:54 GMT
`

I have to cancel the conversion without any result (no new measurement in the influxdb database).
Do you have an advice for me? I am using macOS to run the program and openhab 2.1.

Thank you!

**Comment by CWempe** [comment]
I am no UNIX-expert so I don't know the differences between linux and macOS.
But your problem seems to be that your `date` program doesa not support the parameters the script uses.

So you need to find an equivalent to:

```
tenyearsago=`date +"%Y-%m-%dT%H:%M:%S%:z" --date="10 years ago"`
```

Or you could use these static values:

```
10y:  2007-07-02T16:44:58+02:00
1y:   2016-06-04T16:44:58+02:00
1m:   2017-06-03T16:44:58+02:00
1w:   2017-06-25T16:45:58+02:00
1d:   2017-07-01T16:45:58+02:00
8h:   2017-07-02T08:45:58+02:00
```

btw: the script does not work with OH2.1 for now. :(

**Comment by controlcde** [comment]
As I described in [OpenHAB-Forum](https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761/829?u=controlc): OSX use BSD not GNU so the syntax of date is different. The following lines should work:

```
tenyearsago=`date -v -10y -R +"%Y-%m-%dT%H:%M:%S:%z"`
oneyearago=`date -v -12m -v -28d -R +"%Y-%m-%dT%H:%M:%S:%z"`
onemonthago=`date -v -29d -R +"%Y-%m-%dT%H:%M:%S:%z"`
oneweekago=`date -v -6d -v -23H -v -59M -R +"%Y-%m-%dT%H:%M:%S:%z"`
onedayago=`date -v -23H -v -59M -R +"%Y-%m-%dT%H:%M:%S:%z"`
eighthoursago=`date -v -7H -v -59M -R +"%Y-%m-%dT%H:%M:%S:%z"`
```
