### ISSUE TITLE
Converting only the last 24h

### ISSUE THREAD

**Issue by johannesbonn** [CWempe/rest2influxdb#3]

**Comment by johannesbonn** [comment]
Hi,
Now I tested your tool under openhabian with success. It works flawless but only imports the last 24h of every item. Is it possible for you to take a look at this problem. I have values from nearly one year and don't want to miss them. 

Thanks for your work!

**Comment by CWempe** [comment]
What is the output of the script?
Especially the timestamps!
I guess there is something wrong with them, so the REST interface defaults to "last 24h".

You can manually check the generated timestamps, if you install the [REST addon](http://docs.openhab.org/configuration/restdocs.html) and request the data yourself.

![image](https://user-images.githubusercontent.com/1270359/27927730-fcef5856-628c-11e7-8175-8e9a51082d43.png)

**Comment by johannesbonn** [comment]
Hi,

my output from the last conversion (yesterday evening):

`[19:13:13] openhabian@openhab-lujo:~/rest2influxdb-OH21$ sudo ./rest2influxdb.sh HK_WEATHER1Aussen_Humidity

### timestamps
item: HK_WEATHER1Aussen_Humidity
10y:  2007-07-06T19:15:50+02:00
1y:   2016-06-08T19:15:50+02:00
1m:   2017-06-07T19:15:50+02:00
1w:   2017-06-29T19:16:50+02:00
1d:   2017-07-05T19:16:50+02:00
8h:   2017-07-06T11:16:50+02:00
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0   2173      0 --:--:-- --:--:-- --:--:--  2206
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1308  100  1308    0     0  45460      0 --:--:-- --:--:-- --:--:-- 46714
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38263    0 38263    0     0   458k      0 --:--:-- --:--:-- --:--:--  461k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0  15449      0 --:--:-- --:--:-- --:--:-- 16533
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9599    0  9599    0     0   176k      0 --:--:-- --:--:-- --:--:--  180k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17928    0 17928    0     0   379k      0 --:--:-- --:--:-- --:--:--  389k

### found values: 1257

### Line from 1 to 100
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: c28c3fc3-626e-11e7-8227-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:15:51 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 101 to 200
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: cea8cf43-626e-11e7-8229-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:16:11 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 201 to 300
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: dabcede3-626e-11e7-822a-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:16:31 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 301 to 400
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: e6cbf19a-626e-11e7-822b-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:16:51 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 401 to 500
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: f2ea463e-626e-11e7-822c-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:17:12 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 501 to 600
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: ff0307f6-626e-11e7-822d-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:17:32 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 601 to 700
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 0b0ff303-626f-11e7-822e-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:17:52 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 701 to 800
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 1724fd30-626f-11e7-822f-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:18:12 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 801 to 900
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 2338ddb4-626f-11e7-8230-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:18:33 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 901 to 1000
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 2f5d23cd-626f-11e7-8231-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:18:53 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 1001 to 1100
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 3b72c5a1-626f-11e7-8232-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:19:13 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 1101 to 1200
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 47990cc3-626f-11e7-8233-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:19:34 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### Line from 1201 to 1300
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 53c0d55b-626f-11e7-8234-000000000000
X-Influxdb-Version: 1.3.0
Date: Thu, 06 Jul 2017 17:19:54 GMT

Sleep for 20 seconds to let InfluxDB process the data...

### delete temporary files
`

**Comment by johannesbonn** [comment]
and some parts from the RESTAPI:

The Beginning:
`{
  "name": "HK_WEATHER1Aussen_Humidity",
  "datapoints": "360",
  "data": [
    {
      "time": 1499367840000,
      "state": "72"
    },
    {
      "time": 1499368080000,
      "state": "71.25"
    },
    {
      "time": 1499368320000,
      "state": "71"
    },
    {
      "time": 1499368560000,
      "state": "71"
    },
    {
      "time": 1499368800000,
      "state": "71"
    },`

And the end:

`{
      "time": 1499452080000,
      "state": "34"
    },
    {
      "time": 1499452320000,
      "state": "34"
    },
    {
      "time": 1499452560000,
      "state": "34"
    },
    {
      "time": 1499452800000,
      "state": "34"
    },
    {
      "time": 1499453040000,
      "state": "34"
    },
    {
      "time": 1499453280000,
      "state": "35"
    },
    {
      "time": 1499453520000,
      "state": "36"
    },
    {
      "time": 1499453760000,
      "state": "36"
    },
    {
      "time": 1499454000000,
      "state": "36"
    }
  ]
}`

But I can not read the time stamp???? Is this the problem?

Thank you for your help!

**Comment by CWempe** [comment]
I cannot see why the script should not work. :(

The dates are correctly generated and the time stamps in the RESTAPI format are correct also.
see: http://www.unixtimestamp.com/index.php

When you comment oit the following line at the end of the script you can keep and look into the files that are generated.
https://github.com/CWempe/rest2influxdb/blob/master/rest2influxdb.sh#L86

What does the `HK_WEATHER1Aussen_Humidity_1m.xml` look like?

**Comment by johannesbonn** [comment]
I don't know what happened, but after a restart of openhab, everything was fine.
Thank you für your help and this tool!!!!
