### ISSUE TITLE
Is rest2influxdb already running under oh 2.3?

### ISSUE THREAD

**Issue by johannesbonn** [CWempe/rest2influxdb#4]

**Comment by CWempe** [comment]
I did not continou this scripot because I do not need it anymore.

But you might find some information here:
https://community.openhab.org/t/migrate-your-existing-persistence-data-to-influxdb/30693/10
and here
https://github.com/spieter/rrd4j2influx

**Comment by CWempe** [comment]
Seems to work with openHAB 2.4 now.

https://github.com/CWempe/rest2influxdb/pull/5
